
INSERT INTO Attribute_Type (name, full_name, description) VALUES 
('FOR', 'Força', NULL),
('DES', 'Destreza', NULL),
('CON', 'Constituição', NULL),
('INT', 'Inteligência', NULL),
('SAB', 'Sabedoria', NULL),
('CAR', 'Carisma', NULL);

---

INSERT INTO Skill (name, id_attribute, description) VALUES
('Atletismo', 1, NULL),
('Acrobacia', 2, NULL),
('Furtividade', 2, NULL),
('Prestidigitação', 2, NULL),
('Arcanismo', 4, NULL),
('História', 4, NULL),
('Investigação', 4, NULL),
('Natureza', 4, NULL),
('Religião', 4, NULL),
('Adestrar Animais', 5, NULL),
('Intuição', 5, NULL),
('Medicina', 5, NULL),
('Percepção', 5, NULL),
('Sobrevivência', 5, NULL),
('Atuação', 6, NULL),
('Enganação', 6, NULL),
('Intimidação', 6, NULL),
('Persuasão', 6, NULL);

---

INSERT INTO Alignment (id_alignment, name, description) VALUES
('Leal e Bom (LB)', 'Criaturas em que se pode confiar para fazer o que é correto conforme esperado pela sociedade.'),
('Neutro e Bom (NB)', 'Fazem o melhor que podem para ajudar os outros de acordo com suas necessidades.'),
('Caótico e Bom (CB)', 'Agem de acordo com sua própria consciência, ignorando expectativas alheias.'),
('Leal e Neutro (LN)', 'Seguem leis, tradições ou códigos pessoais de forma consistente.'),
('Neutro (N)', 'Evitam tomar partido moral, agindo conforme a situação parece exigir.'),
('Caótico e Neutro (CN)', 'Seguem seus próprios caprichos, priorizando liberdade pessoal acima de tudo.'),
('Leal e Mau (LM)', 'Buscam seus objetivos de forma metódica dentro de leis ou tradições.'),
('Neutro e Mau (NM)', 'Fazem o que desejam sem compaixão ou remorso.'),
('Caótico e Mau (CM)', 'Agem com violência arbitrária movidos por ganância, ódio ou sede de sangue.');

---
INSERT INTO Armour (name, armour_class_base, is_sum_dexterity, armour_type, max_dexterity_bonus, is_stealth_disadvantage, weight, price_value) VALUES 
-- Armaduras Leves
('Acolchoada', 11, TRUE, 'Armadura Leve', NULL, TRUE, 4.0, 5.0),
('Couro', 11, TRUE, 'Armadura Leve', NULL, FALSE, 5.0, 10.0),
('Couro Batido', 12, TRUE, 'Armadura Leve', NULL, FALSE, 6.5, 45.0),

-- Armaduras Médias
('Gibão de Peles', 12, TRUE, 'Armadura Média', 2, FALSE, 6.0, 10.0),
('Camisão de Malha', 13, TRUE, 'Armadura Média', 2, FALSE, 10.0, 50.0),
('Brunea', 14, TRUE, 'Armadura Média', 2, TRUE, 22.5, 50.0),
('Peitoral', 14, TRUE, 'Armadura Média', 2, FALSE, 10.0, 400.0),
('Meia-Armadura', 15, TRUE, 'Armadura Média', 2, TRUE, 20.0, 750.0),

-- Armaduras Pesadas
('Cota de anéis', 14, FALSE, 'Armadura Pesada', NULL, TRUE, 20.0, 30.0),
('Cota de malha', 16, FALSE, 'Armadura Pesada', NULL, TRUE, 27.5, 75.0),
('Cota de talas', 17, FALSE, 'Armadura Pesada', NULL, TRUE, 30.0, 200.0),
('Placas', 18, FALSE, 'Armadura Pesada', NULL, TRUE, 32.5, 1500.0),

-- Escudo
('Escudo', 2, FALSE, 'Escudo', NULL, FALSE, 3.0, 10.0);

---

INSERT INTO Background (id_background, name, starting_gold_po, languages_number) VALUES
(1, 'Acólito', 15, 2),
(2, 'Artesão de Guilda', 15, 1),
(3, 'Artista', 15, 0),
(4, 'Charlatão', 15, 0),
(5, 'Criminoso', 15, 0),
(6, 'Eremita', 5, 1),
(7, 'Forasteiro', 10, 1),
(8, 'Herói do Povo', 10, 0),
(9, 'Marinheiro', 10, 0),
(10, 'Nobre', 25, 1),
(11, 'Órfão', 10, 0),
(12, 'Sábio', 10, 2),
(13, 'Soldado', 10, 0);

-- Ajustar a sequência do SERIAL após o insert manual
SELECT setval(pg_get_serial_sequence('Background', 'id_background'), (SELECT MAX(id_background) FROM Background));

---

INSERT INTO Class (id_class, name) VALUES
(1, 'Bárbaro'),
(2, 'Bardo'),
(3, 'Bruxo'),
(4, 'Clérigo'),
(5, 'Druida'),
(6, 'Feiticeiro'),
(7, 'Guerreiro'),
(8, 'Ladino'),
(9, 'Mago'),
(10, 'Monge'),
(11, 'Paladino'),
(12, 'Patrulheiro');

-- Sincronizar a sequência do SERIAL
SELECT setval(pg_get_serial_sequence('Class', 'id_class'), (SELECT MAX(id_class) FROM Class));
---

INSERT INTO Weapon (name, damage_die, damage_type, properties, weight, price_value) VALUES
-- Armas Simples Corpo-a-Corpo
('Adaga', '1d4', 'perfurante', 'Acuidade, leve, arremesso (distância 6/18)', 0.5, 2.0),
('Azagaia', '1d6', 'perfurante', 'Arremesso (distância 9/36)', 1.0, 0.5),
('Bordão', '1d6', 'concussão', 'Versátil (1d8)', 2.0, 0.2),
('Clava Grande', '1d8', 'concussão', 'Pesada, duas mãos', 5.0, 0.2),
('Foice Curta', '1d4', 'cortante', 'Leve', 1.0, 1.0),
('Lança', '1d6', 'perfurante', 'Arremesso (distância 6/18), versátil (1d8)', 1.5, 1.0),
('Maça', '1d6', 'concussão', NULL, 2.0, 5.0),
('Machadinha', '1d6', 'cortante', 'Leve, arremesso (distância 6/18)', 1.0, 5.0),
('Martelo Leve', '1d4', 'concussão', 'Leve, arremesso (distância 6/18)', 1.0, 2.0),
('Porrete', '1d4', 'concussão', 'Leve', 1.0, 0.1),

-- Armas Simples à Distância
('Arco Curto', '1d6', 'perfurante', 'Munição (distância 24/96), duas mãos', 1.0, 25.0),
('Besta Leve', '1d8', 'perfurante', 'Munição (distância 24/96), recarga, duas mãos', 2.5, 25.0),
('Dardo', '1d4', 'perfurante', 'Acuidade, arremesso (distância 6/18)', 0.1, 0.05),
('Funda', '1d4', 'concussão', 'Munição (distância 9/36)', 0.0, 0.1),

-- Armas Marciais Corpo-a-Corpo
('Alabarda', '1d10', 'cortante', 'Pesada, alcance, duas mãos', 3.0, 20.0),
('Cimitarra', '1d6', 'cortante', 'Acuidade, leve', 1.5, 25.0),
('Chicote', '1d4', 'cortante', 'Acuidade, alcance', 1.5, 2.0),
('Espada Curta', '1d6', 'perfurante', 'Acuidade, leve', 1.0, 10.0),
('Espada Grande', '2d6', 'cortante', 'Pesada, duas mãos', 3.0, 50.0),
('Espada Longa', '1d8', 'cortante', 'Versátil (1d10)', 1.5, 15.0),
('Glaive', '1d10', 'cortante', 'Pesada, alcance, duas mãos', 3.0, 20.0),
('Lança de Montaria', '1d12', 'perfurante', 'Alcance, especial', 3.0, 10.0),
('Lança Longa', '1d10', 'perfurante', 'Pesada, alcance, duas mãos', 4.0, 5.0),
('Maça Estrela', '1d8', 'perfurante', NULL, 2.0, 15.0),
('Machado Grande', '1d12', 'cortante', 'Pesada, duas mãos', 3.5, 30.0),
('Machado de Batalha', '1d8', 'cortante', 'Versátil (1d10)', 2.0, 10.0),
('Malho', '2d6', 'concussão', 'Pesada, duas mãos', 5.0, 10.0),
('Mangual', '1d8', 'concussão', NULL, 1.0, 10.0),
('Martelo de Guerra', '1d8', 'concussão', 'Versátil (1d10)', 1.0, 15.0),
('Picareta de Guerra', '1d8', 'perfurante', NULL, 1.0, 5.0),
('Rapieira', '1d8', 'perfurante', 'Acuidade', 1.0, 25.0),
('Tridente', '1d6', 'perfurante', 'Arremesso (6/18), versátil (1d8)', 2.0, 5.0),

-- Armas Marciais à Distância
('Arco Longo', '1d8', 'perfurante', 'Munição (distância 45/180), pesada, duas mãos', 1.0, 50.0),
('Besta de Mão', '1d6', 'perfurante', 'Munição (distância 9/36), leve, recarga', 1.5, 75.0),
('Besta Pesada', '1d10', 'perfurante', 'Munição (distância 30/120), pesada, recarga, duas mãos', 4.5, 50.0),
('Rede', NULL, NULL, 'Especial, arremesso (distância 1,5/4,5)', 1.5, 1.0),
('Zarabatana', '1', 'perfurante', 'Munição (distância 7,5/30), recarga', 0.5, 10.0);

-- Sincronizar o contador do ID SERIAL
SELECT setval(pg_get_serial_sequence('Weapon', 'id_weapon'), (SELECT MAX(id_weapon) FROM Weapon));

---

INSERT INTO Item (name, description, price_value, weight) VALUES
('Ábaco', 'Um instrumento usado para cálculos matemáticos rápidos.', 2.0, 1.0),
('Ácido (vidro)', 'Como uma ação, você pode lançar o conteúdo deste vidro em uma criatura a até 6 metros.', 25.0, 0.5),
('Água benta (frasco)', 'Causa dano radiante a mortos-vivos e ínferos se atingidos pelo frasco quebrado.', 25.0, 0.5),
('Algemas', 'Podem prender uma criatura Pequena ou Média. Escapar requer um teste de Destreza (Acrobacia) CD 20.', 2.0, 2.0),
('Algibeira', 'Uma bolsa de couro que pode carregar cerca de 20 moedas ou objetos pequenos.', 5.0, 0.5),
('Aljava', 'Pode carregar até 20 flechas.', 1.0, 0.5),
('Ampulheta', 'Um dispositivo de vidro usado para medir a passagem de uma hora.', 25.0, 0.5),
('Antídoto (vidro)', 'Uma criatura que beber o conteúdo deste vidro tem vantagem em testes de resistência contra veneno por 1 hora.', 50.0, 0.0),
('Apito de advertência', 'Um apito que emite um som agudo audível a grandes distâncias.', 25.0, 0.5),
('Aríete portátil', 'Pode ser usado para quebrar portas, concedendo +4 de bônus no teste de Força.', 4.0, 17.5),
('Armadilha de caça', 'Quando acionada, prende a perna da criatura e causa 1d4 de dano perfurante.', 5.0, 12.5),
('Arpéu', 'Um gancho de metal usado para prender cordas em superfícies.', 2.0, 2.0),
('Balança de mercador', 'Inclui um conjunto de pesos e pratos para medir massa com precisão.', 5.0, 1.5),
('Balde', 'Recipiente de madeira ou metal com alça, capacidade para 12 litros.', 0.05, 1.0),
('Barril', 'Recipiente grande de madeira com capacidade para 150 litros de líquido.', 2.0, 35.0),
('Baú', 'Um receptáculo de madeira ou metal para guardar itens, pode ser trancado.', 5.0, 12.5),
('Bolsa de componentes', 'Uma bolsa que contém todos os materiais necessários para conjurar magias que não possuem custo específico.', 25.0, 1.0),
('Caixa de Fogo', 'Contém pederneira e isqueiro para acender fogueiras ou tochas.', 0.5, 0.5),
('Caneca', 'Um recipiente comum para beber líquidos.', 0.02, 0.5),
('Caneta tinteiro', 'Uma pena ou caneta de metal usada para escrita.', 0.02, 0.0),
('Cantil', 'Um recipiente de couro ou metal para transportar água (capacidade 2 litros).', 0.2, 2.5),
('Cesto', 'Um cesto trançado para transportar mercadorias.', 0.4, 1.0),
('Cobertor de inverno', 'Um cobertor grosso de lã para proteção contra o frio.', 0.5, 1.5),
('Corda de cânhamo (15 metros)', 'Uma corda comum, possui 2 pontos de vida e pode ser rompida com um teste de Força CD 17.', 1.0, 5.0),
('Corda de seda (15 metros)', 'Mais leve e resistente que a de cânhamo, possui 2 pontos de vida e teste de Força CD 17.', 10.0, 2.5),
('Corrente (3 metros)', 'Uma corrente de ferro que pode ser rompida com um teste de Força CD 20.', 5.0, 5.0),
('Equipamento de pescaria', 'Inclui vara, linha, anzóis e iscas.', 1.0, 2.0),
('Escada (3 metros)', 'Uma escada simples de madeira.', 0.1, 12.5),
('Esferas (sacola com 1.000)', 'Podem ser espalhadas no chão para fazer criaturas tropeçarem.', 1.0, 1.0),
('Espelho de aço', 'Um espelho pequeno usado para olhar ao redor de cantos ou sinalizar.', 5.0, 0.25),
('Estrepes (bolsa com 20)', 'Espalhados no chão, podem ferir os pés de quem passar sobre eles.', 1.0, 1.0),
('Fechadura', 'Uma fechadura de ferro que requer uma chave.', 10.0, 0.5),
('Foco arcano: Bastão', 'Um item especial usado como canalizador para magias de feiticeiros, bruxos ou magos.', 10.0, 1.0),
('Foco arcano: Cajado', 'Um cajado longo usado como canalizador de magia arcana.', 5.0, 2.0),
('Foco arcano: Cristal', 'Um cristal lapidado usado para canalizar energia mágica.', 10.0, 0.5),
('Foco arcano: Orbe', 'Uma esfera de vidro ou cristal usada como foco para conjuradores arcanos.', 20.0, 1.5),
('Foco arcano: Varinha', 'Uma varinha curta feita de madeira ou metal para foco arcano.', 10.0, 0.5),
('Foco druídico: Cajado de madeira', 'Um cajado natural usado por druidas para canalizar magias da natureza.', 5.0, 2.0),
('Foco druídico: Ramo de visco', 'Um ramo sagrado usado por druidas como foco de conjuração.', 1.0, 0.0),
('Foco druídico: Totem', 'Um pequeno objeto esculpido com símbolos naturais.', 1.0, 0.0),
('Foco druídico: Varinha de teixo', 'Uma varinha feita da árvore teixo para magias druídicas.', 10.0, 0.5),
('Fogo alquímico (frasco)', 'Lançado contra um alvo, entra em combustão ao contato com o ar.', 50.0, 0.5),
('Frasco', 'Um recipiente de vidro ou argila para líquidos pequenos.', 0.02, 1.0),
('Garrafa de vidro', 'Uma garrafa comum que comporta cerca de 750ml.', 1.0, 1.0),
('Giz (1 peça)', 'Usado para marcar superfícies.', 0.01, 0.0),
('Grimório', 'Um livro contendo fórmulas de magias de um mago.', 50.0, 1.5),
('Jarra', 'Um recipiente de cerâmica para armazenar mantimentos.', 0.04, 2.0),
('Kit de escalada', 'Inclui pítons, luvas, botas com cravos e arnês.', 25.0, 6.0),
('Kit de primeiros-socorros', 'Usado para estabilizar criaturas com 0 pontos de vida sem precisar de um teste de Sabedoria (Medicina).', 5.0, 1.5),
('Lâmpada', 'Emite luz plena em um raio de 4,5 metros e luz fraca por mais 9 metros.', 0.5, 0.5),
('Lanterna coberta', 'Emite luz clara em raio de 9 metros e pode ser fechada para esconder a luz.', 5.0, 1.0),
('Lanterna furta-fogo', 'Direciona um cone de luz clara de 18 metros.', 10.0, 1.0),
('Lente de aumento', 'Concede vantagem em testes de habilidade para analisar objetos pequenos ou detalhados.', 100.0, 0.0),
('Livro', 'Um volume encadernado sobre um assunto específico ou para anotações.', 25.0, 2.5),
('Luneta', 'Usada para observar objetos à distância (magnificação de objetos distantes).', 1000.0, 0.5),
('Manto', 'Uma peça de vestuário exterior que cobre o corpo e a cabeça.', 1.0, 2.0),
('Marreta', 'Um martelo pesado de duas mãos para quebrar rochas ou estruturas.', 2.0, 5.0),
('Martelo', 'Um martelo de mão para trabalho comum ou carpintaria.', 1.0, 1.5),
('Mochila', 'Pode carregar até 15 kg de equipamento.', 2.0, 2.5),
('Munição: Balas de Funda (20)', 'Pedras polidas ou bolas de metal para uso com funda.', 0.04, 0.75),
('Munição: Flechas (20)', 'Munição para arcos.', 1.0, 0.5),
('Munição: Virotes (20)', 'Munição para bestas.', 1.0, 0.75),
('Munição: Zarabatana (50)', 'Pequenos dardos para uso com zarabatana.', 1.0, 0.5),
('Óleo (frasco)', 'Pode ser usado em lanternas ou espalhado para queimar inimigos.', 0.1, 0.5),
('Pá', 'Ferramenta usada para cavar buracos.', 2.0, 2.5),
('Panela de ferro', 'Usada para cozinhar refeições sobre o fogo.', 2.0, 5.0),
('Papel (uma folha)', 'Papel de alta qualidade para escrita.', 0.2, 0.0),
('Parafina', 'Usada para selar recipientes ou lubrificar itens.', 0.5, 0.0),
('Pé de cabra', 'Concede vantagem em testes de Força onde uma alavanca pode ser aplicada.', 2.0, 2.5),
('Pedra de amolar', 'Usada para manter as lâminas de espadas e machados afiadas.', 0.01, 0.0),
('Perfume (frasco)', 'Líquido aromático para disfarçar odores.', 5.0, 0.0),
('Pergaminho (uma folha)', 'Pele de animal tratada para escrita durável.', 0.1, 0.0),
('Picareta de minerador', 'Ferramenta usada para escavação em rocha.', 2.0, 5.0),
('Píton', 'Pinos de metal usados para fixar cordas em paredes durante escaladas.', 0.05, 0.0),
('Poção de cura', 'Recupera 2d4 + 2 pontos de vida quando ingerida.', 50.0, 0.25),
('Porta mapas ou pergaminhos', 'Um tubo de couro usado para proteger papéis importantes.', 1.0, 0.5),
('Porta virotes', 'Um estojo para carregar virotes de besta.', 1.0, 0.5),
('Pregos de ferro (10)', 'Pregos resistentes para fixações diversas.', 1.0, 2.5),
('Rações de viagem (1 dia)', 'Comida seca e preservada para aventureiros em trânsito.', 0.5, 1.0),
('Robes', 'Vestimentas largas e leves comuns entre acadêmicos e magos.', 1.0, 2.0),
('Roldana e polia', 'Um sistema de polias para ajudar a levantar cargas pesadas.', 1.0, 2.5),
('Roupas comuns', 'Roupas simples usadas por camponeses ou cidadãos médios.', 0.5, 1.5),
('Roupas de viajante', 'Roupas resistentes e práticas para climas variados e estradas.', 2.0, 2.0),
('Roupas de entretenimento', 'Trajes coloridos e chamativos para artistas e bardos.', 5.0, 2.0),
('Roupas finas', 'Roupas luxuosas e elegantes para eventos nobres.', 15.0, 3.0),
('Sabão', 'Barra usada para higiene pessoal.', 0.02, 0.0),
('Saco', 'Um saco de pano resistente capaz de carregar 15 kg.', 0.01, 0.25),
('Saco de dormir', 'Um isolante térmico de tecido para dormir ao relento.', 1.0, 3.5),
('Símbolo sagrado: Amuleto', 'Um símbolo religioso usado em volta do pescoço por clérigos ou paladinos.', 5.0, 0.5),
('Símbolo sagrado: Emblema', 'Um símbolo sagrado cravado ou pintado em um escudo.', 5.0, 0.0),
('Símbolo sagrado: Relicário', 'Um pequeno receptáculo contendo uma relíquia religiosa sagrada.', 5.0, 1.0),
('Sinete', 'Um anel ou carimbo usado para selar documentos com cera.', 5.0, 0.0),
('Sino', 'Um pequeno sino de metal para avisos ou alarmes.', 1.0, 0.0),
('Tenda para duas pessoas', 'Uma estrutura de lona portátil para acampamento.', 2.0, 10.0),
('Tocha', 'Queima por 1 hora, emitindo luz clara em um raio de 6 metros.', 0.01, 0.5),
('Tinta (frasco de 30ml)', 'Tinta escura usada para escrever com penas.', 10.0, 0.0),
('Vara (3 metros)', 'Uma vara de madeira usada para testar armadilhas ou profundidade.', 0.05, 3.5),
('Vela', 'Emite luz plena em um raio de 1,5 metros por 1 hora.', 0.01, 0.0),
('Veneno básico (frasco)', 'Pode ser aplicado em uma arma; a criatura atingida deve passar em um teste de Constituição CD 10.', 100.0, 0.0);

---

INSERT INTO Race (id_race, name, movement) VALUES
(1, 'Anão', '7,5'),
(2, 'Elfo', '9'),
(3, 'Halfling', '7,5'),
(4, 'Draconato', '9'),
(5, 'Gnomo', '7,5'),
(6, 'Meio-Elfo', '9'),
(7, 'Meio-Orc', '9'),
(8, 'Tiefling', '9'),
(9, 'Humano', '9');

-- Sincronizar a sequência do SERIAL após a inserção manual
SELECT setval(pg_get_serial_sequence('Race', 'id_race'), (SELECT MAX(id_race) FROM Race));

---

INSERT INTO Spell (name, description, casting_time, range_distance, duration, damage, is_verbal, is_somatic, is_material, spellLevel, school) VALUES
('Acalmar Emoções', 'Você tenta suprimir emoções fortes em um grupo de pessoas em uma esfera de 6 metros.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 2, 'Encantamento'),
('Adivinhação', 'Você faz uma única pergunta a respeito de um objetivo ou evento que irá ocorrer dentro de 7 dias.', '1 ação', 0, 'Instantânea', NULL, TRUE, TRUE, TRUE, 4, 'Adivinhação'),
('Ajuda', 'O máximo de pontos de vida e os pontos de vida atuais de cada alvo aumentam em 5.', '1 ação', 9, '8 horas', NULL, TRUE, TRUE, TRUE, 2, 'Abjuração'),
('Alarme', 'Você coloca um alarme para intrusos em uma área que não seja maior que 6 metros cúbicos.', '1 minuto', 9, '8 horas', NULL, TRUE, TRUE, TRUE, 1, 'Abjuração'),
('Aliado Planar', 'Você suplica a uma entidade transcendental por ajuda de um celestial, corruptor ou elemental.', '10 minutos', 18, 'Instantânea', NULL, TRUE, TRUE, FALSE, 6, 'Conjuração'),
('Aljava Veloz', 'Transmuta sua aljava para que ela produza um suprimento interminável de munições não-mágicas.', '1 ação bônus', 1, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 5, 'Transmutação'),
('Alterar Forma', 'Você assume a forma de uma criatura diferente com ND igual ao seu nível ou menor.', '1 ação', 0, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 9, 'Transmutação'),
('Alterar-se', 'Você assume uma forma diferente: Adaptação Aquática, Mudar Aparência ou Armas Naturais.', '1 ação', 0, 'Concentração, até 1 hora', '1d6', TRUE, TRUE, FALSE, 2, 'Transmutação'),
('Amizade', 'Você terá vantagem em todos os testes de Carisma direcionados a uma criatura não hostil.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, FALSE, TRUE, TRUE, 0, 'Encantamento'),
('Amizade Animal', 'Convence uma besta que você não quer prejudicá-la através de um teste de Sabedoria.', '1 ação', 9, '24 horas', NULL, TRUE, TRUE, TRUE, 1, 'Encantamento'),
('Ampliar Plantas', 'Canaliza vitalidade nas plantas tornando-as espessas ou fertilizando a terra.', '1 ação ou 8 horas', 45, 'Instantânea', NULL, TRUE, TRUE, FALSE, 3, 'Transmutação'),
('Âncora Planar', 'Você tenta obrigar um celestial, corruptor, elemental ou fada a servi-lo.', '1 hora', 18, '24 horas', NULL, TRUE, TRUE, TRUE, 5, 'Abjuração'),
('Andar na Água', 'Concede a habilidade de se mover através de qualquer superfície líquida como se fosse chão sólido.', '1 ação', 9, '1 hora', NULL, TRUE, TRUE, TRUE, 3, 'Transmutação'),
('Animar Mortos', 'Cria um servo morto-vivo esqueleto ou zumbi a partir de um corpo ou ossos.', '1 minuto', 3, 'Instantânea', NULL, TRUE, TRUE, TRUE, 3, 'Necromancia'),
('Animar Objetos', 'Até dez objetos não-mágicos ganham vida e tornam-se criaturas sob seu controle.', '1 ação', 36, 'Concentração, até 1 minuto', '1d4+4', TRUE, TRUE, FALSE, 5, 'Transmutação'),
('Antipatia/Simpatia', 'Envolve um alvo com uma aura que atrai ou repele criaturas de um tipo específico.', '1 hora', 18, '10 dias', NULL, TRUE, TRUE, TRUE, 8, 'Encantamento'),
('Aprimorar Habilidade', 'Agracia uma criatura com um aprimoramento mágico como Vigor do Urso ou Agilidade do Gato.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Aprisionamento', 'Cria um impedimento mágico para imobilizar uma criatura de forma permanente até ser dissipada.', '1 minuto', 9, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 9, 'Abjuração'),
('Arca Secreta de Leomund', 'Esconde um baú e todo o seu conteúdo no Plano Etéreo para ser revocado depois.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 4, 'Conjuração'),
('Área Escorregadia', 'Cobre o solo com graxa tornando a área em terreno difícil e derrubando criaturas.', '1 ação', 18, '1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Conjuração'),
('Arma Elemental', 'Uma arma não-mágica se torna mágica e causa dano extra de ácido, elétrico, frio, fogo ou trovão.', '1 ação', 1, 'Concentração, até 1 hora', '1d4', TRUE, TRUE, FALSE, 3, 'Transmutação'),
('Arma Espiritual', 'Cria uma arma espectral flutuante que realiza ataques corpo-a-corpo com magia.', '1 ação bônus', 18, '1 minuto', '1d8', TRUE, TRUE, FALSE, 2, 'Evocação'),
('Arma Mágica', 'Toca uma arma não-mágica concedendo +1 de bônus nas jogadas de ataque e dano.', '1 ação bônus', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 2, 'Transmutação'),
('Armadura Arcana', 'Uma energia mágica protetora envolve um alvo sem armadura, definindo a CA base para 13 + Des.', '1 ação', 1, '8 horas', NULL, TRUE, TRUE, TRUE, 1, 'Abjuração'),
('Armadura de Agathys', 'Um frio espectral cobre você, garantindo 5 PV temporários e causando 5 de dano de frio a atacantes.', '1 ação', 0, '1 hora', '5', TRUE, TRUE, TRUE, 1, 'Abjuração'),
('ArromBAR', 'Destranca ou desbloqueia uma porta, baú ou algemas, suprimindo trancas arcanas.', '1 ação', 18, 'Instantânea', NULL, TRUE, FALSE, FALSE, 2, 'Transmutação'),
('Assassino Fantasmagórico', 'Cria uma manifestação ilusória dos medos mais profundos de um alvo causando dano psíquico.', '1 ação', 36, 'Concentração, até 1 minuto', '4d10', TRUE, TRUE, FALSE, 4, 'Ilusão'),
('Ataque Certeiro', 'Garante uma breve intuição sobre as defesas do alvo, dando vantagem na próxima jogada de ataque.', '1 ação', 9, 'Concentração, até 1 rodada', NULL, FALSE, TRUE, FALSE, 0, 'Adivinhação'),
('Ataque Visual', 'Seus olhos emitem poder terrível que pode adormecer, apavorar ou adoecer criaturas.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 6, 'Necromancia'),
('Augúrio', 'Você recebe um presságio de uma entidade sobre os resultados de uma ação planejada.', '1 minuto', 0, 'Instantânea', NULL, TRUE, TRUE, TRUE, 2, 'Adivinhação'),
('Aumentar/Reduzir', 'Faz com que uma criatura ou objeto fique maior ou menor, alterando seu peso e dano.', '1 ação', 9, 'Concentração, até 1 minuto', '1d4', TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Aura de Pureza', 'Energia purificante impede doenças e concede resistência a veneno em uma aura de 9 metros.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, FALSE, FALSE, 4, 'Abjuração'),
('Aura de Vida', 'Criaturas não-hostis na aura ganham resistência a dano necrótico e recuperam 1 PV se estiverem com 0.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, FALSE, FALSE, 4, 'Abjuração'),
('Aura de Vitalidade', 'Você pode usar uma ação bônus para fazer com que uma criatura na aura recupere 2d6 PV.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, FALSE, FALSE, 3, 'Evocação'),
('Aura Mágica de Nystul', 'Coloca uma ilusão em uma criatura ou objeto para enganar magias de adivinhação.', '1 ação', 1, '24 horas', NULL, TRUE, TRUE, TRUE, 2, 'Ilusão'),
('Aura Sagrada', 'Luz divina concede vantagem em testes de resistência e impõe desvantagem em ataques contra aliados.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 8, 'Abjuração'),
('Auxílio Divino', 'Sua oração fortalece você, fazendo com que seus ataques com arma causem 1d4 de dano radiante extra.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '1d4', TRUE, TRUE, FALSE, 1, 'Evocação'),
('Banimento', 'Tenta enviar uma criatura para outro plano de existência se ela falhar no teste de Carisma.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 4, 'Abjuração'),
('Banquete de Heróis', 'Traz um grande banquete que cura doenças, venenos e aumenta o máximo de pontos de vida.', '10 minutos', 9, 'Instantânea', NULL, TRUE, TRUE, TRUE, 6, 'Conjuração'),
('Barreira de Lâminas', 'Cria uma muralha de lâminas giratórias que causa 6d10 de dano cortante.', '1 ação', 24, 'Concentração, até 10 minutos', '6d10', TRUE, TRUE, FALSE, 6, 'Evocação'),
('Bênção', 'Abençoa até três criaturas adicionando 1d4 às suas jogadas de ataque e testes de resistência.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Encantamento'),
('Boca Encantada', 'Implanta uma mensagem em um objeto que é pronunciada quando uma condição é satisfeita.', '1 minuto', 9, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 2, 'Ilusão'),
('Bola de Fogo', 'Uma explosão de chamas em uma esfera de 6 metros que causa 8d6 de dano de fogo.', '1 ação', 45, 'Instantânea', '8d6', TRUE, TRUE, TRUE, 3, 'Evocação'),
('Bola de Fogo Controlável', 'Uma conta de luz que acumula dano e explode em chamas após a concentração terminar.', '1 ação', 45, 'Concentração, até 1 minuto', '12d6', TRUE, TRUE, TRUE, 7, 'Evocação'),
('Bom Fruto', 'Cria frutos que restauram 1 ponto de vida e fornecem nutrição para um dia inteiro.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 1, 'Transmutação'),
('Bordão Místico', 'Imbui um bordão com poder da natureza usando seu atributo de conjuração para ataque e dano.', '1 ação bônus', 1, '1 minuto', '1d8', TRUE, TRUE, TRUE, 0, 'Transmutação'),
('Braços de Hadar', 'Tentáculos de energia negra surgem de você causando dano necrótico e impedindo reações.', '1 ação', 0, 'Instantânea', '2d6', TRUE, TRUE, FALSE, 1, 'Conjuração'),
('Bruxaria', 'Coloca uma maldição em uma criatura causando 1d6 de dano necrótico extra ao atingi-la.', '1 ação bônus', 18, 'Concentração, até 1 hora', '1d6', TRUE, TRUE, TRUE, 1, 'Encantamento'),
('Caminhar em Árvores', 'Permite que você entre em uma árvore e se mova para outra do mesmo tipo a até 150 metros.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 5, 'Conjuração'),
('Caminhar no Vento', 'Transforma até dez criaturas em forma gasosa de nuvem com deslocamento de voo de 90 metros.', '1 minuto', 9, '8 horas', NULL, TRUE, TRUE, TRUE, 6, 'Transmutação'),
('Campo Antimagia', 'Uma esfera de 3 metros que anula magias, itens mágicos e criaturas invocadas.', '1 ação', 0, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 8, 'Abjuração'),
('Cão Fiel de Mordenkainen', 'Conjura um cão de guarda fantasma invisível que ataca inimigos próximos.', '1 ação', 9, '8 horas', '4d8', TRUE, TRUE, TRUE, 4, 'Conjuração'),
('Cativar', 'Você tece palavras distrativas que impõe desvantagem em testes de Percepção para notar outros.', '1 ação', 18, '1 minuto', NULL, TRUE, TRUE, FALSE, 2, 'Encantamento'),
('Carne para Pedra', 'Tenta transformar uma criatura em pedra através de sucessivos testes de Constituição.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 6, 'Transmutação'),
('Cegueira/Surdez', 'O alvo deve ser bem sucedido num teste de Constituição ou ficará cego ou surdo.', '1 ação', 9, '1 minuto', NULL, TRUE, FALSE, FALSE, 2, 'Necromancia'),
('Chama Contínua', 'Uma chama que não produz calor surge de um objeto e dura até ser dissipada.', '1 ação', 1, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 2, 'Evocação'),
('Chama Sagrada', 'Radiação similar a uma chama desce sobre uma criatura causando 1d8 de dano radiante.', '1 ação', 18, 'Instantânea', '1d8', TRUE, TRUE, FALSE, 0, 'Evocação'),
('Chicote de Espinhos', 'Cria um chicote de vinhas que causa 1d6 de dano perfurante e puxa o alvo.', '1 ação', 9, 'Instantânea', '1d6', TRUE, TRUE, TRUE, 0, 'Transmutação'),
('Chuva de Meteoros', 'Quatro esferas de fogo atingem o solo causando 20d6 de fogo e 20d6 de concussão.', '1 ação', 1500, 'Instantânea', '40d6', TRUE, TRUE, FALSE, 9, 'Evocação'),
('Círculo da Morte', 'Uma esfera de energia negativa causa 8d6 de dano necrótico em um raio de 18 metros.', '1 ação', 45, 'Instantânea', '8d6', TRUE, TRUE, TRUE, 6, 'Necromancia'),
('Círculo de Poder', 'Concede vantagem em testes contra magias e anula danos em sucessos na resistência.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, FALSE, FALSE, 5, 'Abjuração'),
('Círculo de Teletransporte', 'Desenha um círculo que conecta sua localização a um círculo de teletransporte permanente.', '1 minuto', 3, '1 rodada', NULL, TRUE, FALSE, TRUE, 5, 'Conjuração'),
('Círculo Mágico', 'Cria um cilindro que protege contra celestiais, corruptores, elementais, fadas ou mortos-vivos.', '1 minuto', 3, '1 hora', NULL, TRUE, TRUE, TRUE, 3, 'Abjuração'),
('Clarividência', 'Cria um sensor invisível em um local para que você possa ver ou ouvir através dele.', '10 minutos', 1500, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 3, 'Adivinhação'),
('Clone', 'Produz uma duplicata inerte de uma criatura viva como garantia contra a morte.', '1 hora', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 8, 'Necromancia'),
('Coluna de Chamas', 'Uma coluna vertical de fogo divino causa dano de fogo e dano radiante.', '1 ação', 18, 'Instantânea', '8d6', TRUE, TRUE, TRUE, 5, 'Evocação'),
('Comando', 'O alvo deve seguir uma palavra de comando como Aproxime-se, Largue, Fuja ou Deite-se.', '1 ação', 18, '1 rodada', NULL, TRUE, FALSE, FALSE, 1, 'Encantamento'),
('Compreender Idiomas', 'Você compreende o significado literal de qualquer idioma falado ou escrito que vir.', '1 ação', 0, '1 hora', NULL, TRUE, TRUE, TRUE, 1, 'Adivinhação'),
('Compulsão', 'Força criaturas a se moverem em uma direção específica em seus turnos.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 4, 'Encantamento'),
('Comunhão', 'Você contata sua divindade e faz até três perguntas de sim ou não.', '1 minuto', 0, '1 minuto', NULL, TRUE, TRUE, TRUE, 5, 'Adivinhação'),
('Comunhão com a Natureza', 'Você se torna um com a natureza e ganha conhecimento do território ao seu redor.', '1 minuto', 0, 'Instantânea', NULL, TRUE, TRUE, FALSE, 5, 'Adivinhação'),
('Cone de Frio', 'Uma explosão de ar gelado causa 8d8 de dano de frio em um cone de 18 metros.', '1 ação', 0, 'Instantânea', '8d8', TRUE, TRUE, TRUE, 5, 'Evocação'),
('Confusão', 'Embaralha as mentes das criaturas gerando delírios e ações descontroladas.', '1 ação', 27, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 4, 'Encantamento'),
('Conhecimento Lendário', 'Traz à mente um breve resumo do conhecimento significativo sobre uma pessoa, local ou objeto.', '10 minutos', 0, 'Instantânea', NULL, TRUE, TRUE, TRUE, 5, 'Adivinhação'),
('Conjurar Animais', 'Invoca espíritos feéricos que assumem formas de bestas amigáveis.', '1 ação', 18, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 3, 'Conjuração'),
('Conjurar Celestial', 'Invoca um celestial de ND 4 ou inferior para ajudar em batalha.', '1 minuto', 27, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 7, 'Conjuração'),
('Conjurar Elementais Menores', 'Invoca oito, quatro, dois ou um elemental dependendo do nível de desafio.', '1 minuto', 27, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 4, 'Conjuração'),
('Conjurar Elemental', 'Invoca um servo elemental de ND 5 ou inferior adequado à área escolhida.', '1 minuto', 27, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 5, 'Conjuração'),
('Conjurar Fada', 'Invoca uma criatura feérica de ND 6 ou inferior que obedece seus comandos.', '1 minuto', 27, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 6, 'Conjuração'),
('Conjurar Rajada', 'Arremessa uma arma ou munição para criar um cone de armas idênticas causando 3d8 de dano.', '1 ação', 0, 'Instantânea', '3d8', TRUE, TRUE, TRUE, 3, 'Conjuração'),
('Conjurar Saraivada', 'Centenas de duplicatas de munição caem em uma saraivada causando 8d8 de dano.', '1 ação', 45, 'Instantânea', '8d8', TRUE, TRUE, TRUE, 5, 'Conjuração'),
('Conjurar Seres da Floresta', 'Invoca criaturas feéricas da floresta como dríades ou sátiros.', '1 ação', 18, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 4, 'Conjuração'),
('Consagrar', 'Infunde uma área com poder sagrado ou profano impedindo fadas, mortos-vivos, etc.', '24 horas', 1, 'Até ser dissipada', '5d6', TRUE, TRUE, TRUE, 5, 'Evocação'),
('Consertar', 'Repara uma única quebra ou fissura em um objeto que você tocar.', '1 minuto', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 0, 'Transmutação'),
('Constrição', 'Vinhas poderosas brotam do solo impedindo o movimento de criaturas.', '1 ação', 27, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 1, 'Conjuração'),
('Contato Extraplanar', 'Você contata uma entidade misteriosa de outro plano para fazer cinco perguntas.', '1 minuto', 0, '1 minuto', '6d6', TRUE, FALSE, FALSE, 5, 'Adivinhação'),
('Contramágica', 'Tenta interromper uma criatura no processo de conjuração de uma magia.', '1 reação', 18, 'Instantânea', NULL, FALSE, TRUE, FALSE, 3, 'Abjuração'),
('Contingência', 'Prepara uma magia de 5 nível ou inferior para se ativar em uma circunstância específica.', '10 minutos', 0, '10 dias', NULL, TRUE, TRUE, TRUE, 6, 'Evocação'),
('Controlar a Água', 'Você controla corpos de água criando inundações, redemoinhos ou dividindo as águas.', '1 ação', 90, 'Concentração, até 10 minutos', '2d8', TRUE, TRUE, TRUE, 4, 'Transmutação'),
('Controlar o Clima', 'Você toma controle das condições climáticas em uma área de 7,5 quilômetros.', '10 minutos', 0, 'Concentração, até 8 horas', NULL, TRUE, TRUE, TRUE, 8, 'Transmutação'),
('Convocar Familiar', 'Adquire os serviços de um espírito que toma a forma de um animal como coruja ou gato.', '1 hora', 3, 'Instantânea', NULL, TRUE, TRUE, TRUE, 1, 'Conjuração'),
('Convocar Montaria', 'Convoca um espírito inteligente e leal que assume a forma de um cavalo ou similar.', '10 minutos', 9, 'Instantânea', NULL, TRUE, TRUE, FALSE, 2, 'Conjuração'),
('Convocar Relâmpagos', 'Relâmpagos são disparados de uma nuvem tempestuosa causando 3d10 de dano elétrico.', '1 ação', 36, 'Concentração, até 10 minutos', '3d10', TRUE, TRUE, FALSE, 3, 'Conjuração'),
('Coroa da Loucura', 'O alvo fica enfeitiçado e deve atacar uma criatura que você escolher mentalmente.', '1 ação', 36, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 2, 'Encantamento'),
('Cordão de Flechas', 'Quatro munições fincadas no solo disparam contra criaturas que se aproximarem.', '1 ação', 1, '8 horas', '1d6', TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Corrente de Relâmpagos', 'Um raio elétrico atinge um alvo e salta para outros três alvos próximos.', '1 ação', 45, 'Instantânea', '10d8', TRUE, TRUE, TRUE, 6, 'Evocação'),
('Crescer Espinhos', 'O solo se retorce brotando espinhos que causam dano a cada 1,5 metro percorrido.', '1 ação', 45, 'Concentração, até 10 minutos', '2d4', TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Criação', 'Você puxa mechas da Umbra para criar objetos de matéria vegetal, mineral ou metal.', '1 minuto', 9, 'Especial', NULL, TRUE, TRUE, TRUE, 5, 'Ilusão'),
('Criar Alimentos', 'Cria 25 quilos de comida e 100 litros de água suficientes para 15 humanoides.', '1 ação', 9, 'Instantânea', NULL, TRUE, TRUE, FALSE, 3, 'Conjuração'),
('Criar Chamas', 'Uma chama aparece em sua mão emitindo luz e podendo ser arremessada.', '1 ação', 0, '10 minutos', '1d8', TRUE, TRUE, FALSE, 0, 'Conjuração'),
('Criar Mortos-Vivos', 'Transforma corpos em carniçais sob seu controle (apenas durante a noite).', '1 minuto', 3, 'Instantânea', NULL, TRUE, TRUE, TRUE, 6, 'Necromancia'),
('Criar ou Destruir Água', 'Cria água limpa em um recipiente ou destrói névoas.', '1 ação', 9, 'Instantânea', NULL, TRUE, TRUE, TRUE, 1, 'Transmutação'),
('Criar Passagem', 'Uma passagem aparece em uma superfície de madeira, gesso ou rocha.', '1 ação', 9, '1 hora', NULL, TRUE, TRUE, TRUE, 5, 'Transmutação'),
('Cúpula Antivida', 'Barreira que restringe criaturas diferentes de mortos-vivos e constructos.', '1 ação', 0, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 5, 'Abjuração'),
('Cura Completa', 'Um surto de energia positiva restaura 70 pontos de vida e cura doenças.', '1 ação', 18, 'Instantânea', NULL, TRUE, TRUE, FALSE, 6, 'Evocação'),
('Cura Completa em Massa', 'Restaura 700 pontos de vida divididos entre criaturas à sua escolha.', '1 ação', 18, 'Instantânea', NULL, TRUE, TRUE, FALSE, 9, 'Evocação'),
('Curar Ferimentos', 'Restaura PV igual a 1d8 + modificador de habilidade de conjuração.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, FALSE, 1, 'Evocação'),
('Curar Ferimentos em Massa', 'Onda de energia curativa restaura 3d8 PV em até seis criaturas.', '1 ação', 18, 'Instantânea', NULL, TRUE, TRUE, FALSE, 5, 'Evocação'),
('Dança Irresistível de Otto', 'O alvo começa a dançar comicamente, tendo desvantagem em ataques e CA.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, FALSE, FALSE, 6, 'Encantamento'),
('Dedo da Morte', 'Envia energia negativa causando 7d8 + 30 de dano necrótico e criando zumbis.', '1 ação', 18, 'Instantânea', '7d8+30', TRUE, TRUE, FALSE, 7, 'Necromancia'),
('Desejo', 'A magia mais poderosa que permite alterar a realidade ou copiar qualquer magia de 8 nível.', '1 ação', 0, 'Instantânea', NULL, TRUE, FALSE, FALSE, 9, 'Conjuração'),
('Desintegrar', 'Raio verde que causa 10d6 + 40 de dano e desintegra o alvo se PV chegar a 0.', '1 ação', 18, 'Instantânea', '10d6+40', TRUE, TRUE, TRUE, 6, 'Transmutação'),
('Despedaçar', 'Um som estridente causa 3d8 de dano trovejante em uma esfera de 3 metros.', '1 ação', 18, 'Instantânea', '3d8', TRUE, TRUE, TRUE, 2, 'Evocação'),
('Despertar', 'Concede inteligência e fala a uma besta ou planta após 8 horas de ritual.', '8 horas', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 5, 'Transmutação'),
('Despistar', 'Você fica invisível e cria uma cópia ilusória sua simultaneamente.', '1 ação', 0, 'Concentração, até 1 hora', NULL, FALSE, TRUE, FALSE, 5, 'Ilusão'),
('Destruição Banidora', 'Ataque causa 5d6 de dano de energia e bane o alvo para outro plano.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '5d6', TRUE, FALSE, FALSE, 5, 'Abjuração'),
('Destruição Cegante', 'Ataque causa 3d8 de dano radiante e deixa o alvo cego.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '3d8', TRUE, FALSE, FALSE, 3, 'Evocação'),
('Destruição Colérica', 'Ataque causa 1d6 de dano psíquico e amedronta o alvo.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '1d6', TRUE, FALSE, FALSE, 1, 'Evocação'),
('Destruição Estonteante', 'Ataque causa 4d6 de dano psíquico e impõe desvantagem em ataques do alvo.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '4d6', TRUE, FALSE, FALSE, 4, 'Evocação'),
('Destruição Lancinante', 'Ataque causa 1d6 de dano de fogo extra e incendeia o alvo.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '1d6', TRUE, FALSE, FALSE, 1, 'Evocação'),
('Destruição Troveante', 'Ataque causa 2d6 de dano trovejante e pode derrubar o alvo no chão.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '2d6', TRUE, FALSE, FALSE, 1, 'Evocação'),
('Detectar o Bem e Mal', 'Sente a presença de aberrações, celestiais, corruptores, fadas ou mortos-vivos.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 1, 'Adivinhação'),
('Detectar Magia', 'Sente a presença de magia e vê uma aura ao redor de objetos ou criaturas mágicas.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 1, 'Adivinhação'),
('Detectar Pensamentos', 'Lê pensamentos superficiais ou sonda profundamente a mente de uma criatura.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 2, 'Adivinhação'),
('Detectar Veneno e Doença', 'Sente a presença e localização de venenos e doenças a até 9 metros.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 1, 'Adivinhação'),
('Dificultar Detecção', 'Esconde um alvo de magias de adivinhação ou sensores mágicos.', '1 ação', 1, '8 horas', NULL, TRUE, TRUE, TRUE, 3, 'Abjuração'),
('Disco Flutuante de Tenser', 'Cria um plano circular de energia que suporta até 250 quilos e segue você.', '1 ação', 9, '1 hora', NULL, TRUE, TRUE, TRUE, 1, 'Conjuração'),
('Disfarçar-se', 'Muda sua aparência física e de seus pertences por uma hora.', '1 ação', 0, '1 hora', NULL, TRUE, TRUE, FALSE, 1, 'Ilusão'),
('Dissipar Magia', 'Encerra magias de nível inferior automaticamente ou através de teste para níveis superiores.', '1 ação', 36, 'Instantânea', NULL, TRUE, TRUE, FALSE, 3, 'Abjuração'),
('Dissipar o Bem e Mal', 'Protege contra fadas, mortos-vivos e planares, podendo bani-los com um toque.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 5, 'Abjuração'),
('Doença Plena', 'Introduz uma doença que causa 14d6 de dano necrótico e reduz o PV máximo.', '1 ação', 18, 'Instantânea', '14d6', TRUE, TRUE, FALSE, 6, 'Necromancia'),
('Dominar Besta', 'Estabelece ligação telepática e controle total sobre uma besta.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 4, 'Encantamento'),
('Dominar Monstro', 'Estabelece ligação telepática e controle total sobre qualquer tipo de criatura.', '1 ação', 18, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 8, 'Encantamento'),
('Dominar Pessoa', 'Estabelece ligação telepática e controle total sobre um humanoide.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 5, 'Encantamento'),
('Druidismo', 'Cria efeitos sensoriais menores da natureza como florescer ou prever o clima.', '1 ação', 9, 'Instantânea', NULL, TRUE, TRUE, FALSE, 0, 'Transmutação'),
('Duelo Compelido', 'Tenta forçar uma criatura a duelar com você, dando desvantagem em ataques contra outros.', '1 ação bônus', 9, 'Concentração, até 1 minuto', NULL, TRUE, FALSE, FALSE, 1, 'Encantamento'),
('Encarnação Fantasmagórica', 'Manifesta pesadelos nas mentes de um grupo causando 4d10 de dano psíquico.', '1 ação', 36, 'Concentração, até 1 minuto', '4d10', TRUE, TRUE, FALSE, 9, 'Ilusão'),
('Encontrar Armadilhas', 'Sente a presença e natureza de qualquer armadilha dentro do alcance.', '1 ação', 36, 'Instantânea', NULL, TRUE, TRUE, FALSE, 2, 'Adivinhação'),
('Encontrar o Caminho', 'Permite encontrar a rota física mais curta para um local específico conhecido.', '1 minuto', 0, 'Concentração, até 1 dia', NULL, TRUE, TRUE, TRUE, 6, 'Adivinhação'),
('Enfeitiçar Pessoa', 'O alvo fica enfeitiçado e passa a considerar você um conhecido amigável.', '1 ação', 9, '1 hora', NULL, TRUE, TRUE, FALSE, 1, 'Encantamento'),
('Enfraquecer Intelecto', 'Ataca a mente do alvo reduzindo Inteligência e Carisma para 1.', '1 ação', 45, 'Instantânea', '4d6', TRUE, TRUE, TRUE, 8, 'Encantamento'),
('Enviar Mensagem', 'Envia uma mensagem mental de até 25 palavras para uma criatura familiar.', '1 ação', 9999, '1 rodada', NULL, TRUE, TRUE, TRUE, 3, 'Evocação'),
('Escrita Ilusória', 'Escreve uma mensagem que parece normal para alguns e inteligível para outros.', '1 minuto', 1, '10 dias', NULL, FALSE, FALSE, TRUE, 1, 'Ilusão'),
('Escudo Arcano', 'Barreira invisível que concede +5 de CA e imunidade a Mísseis Mágicos.', '1 reação', 0, '1 rodada', NULL, TRUE, TRUE, FALSE, 1, 'Abjuração'),
('Escudo da Fé', 'Campo cintilante que concede +2 de bônus na CA.', '1 ação bônus', 18, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 1, 'Abjuração'),
('Escudo de Fogo', 'Chamas rodeiam seu corpo dando resistência a dano e retribuindo dano a atacantes.', '1 ação', 0, '10 minutos', '2d8', TRUE, TRUE, TRUE, 4, 'Evocação'),
('Escuridão', 'Cria uma esfera de 4,5 metros de escuridão mágica que bloqueia visão no escuro.', '1 ação', 18, 'Concentração, até 10 minutos', NULL, TRUE, FALSE, TRUE, 2, 'Evocação'),
('Esfera Congelante de Otiluke', 'Globo frigido que causa 10d6 de dano de frio em uma esfera de 18 metros.', '1 ação', 90, 'Instantânea', '10d6', TRUE, TRUE, TRUE, 6, 'Evocação'),
('Esfera Flamejante', 'Esfera de fogo de 1,5 metro que pode ser movida e causa 2d6 de dano.', '1 ação', 18, 'Concentração, até 1 minuto', '2d6', TRUE, TRUE, TRUE, 2, 'Conjuração'),
('Esfera Resiliente de Otiluke', 'Esfera de energia que aprisiona uma criatura ou objeto impedindo qualquer dano.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 4, 'Evocação'),
('Espada de Mordenkainen', 'Espada de energia flutuante que causa 3d10 de dano de energia.', '1 ação', 18, 'Concentração, até 1 minuto', '3d10', TRUE, TRUE, TRUE, 7, 'Evocação'),
('Espíritos Guardiões', 'Espíritos flutuam ao seu redor causando 3d8 de dano radiante ou necrótico.', '1 ação', 0, 'Concentração, até 10 minutos', '3d8', TRUE, TRUE, TRUE, 3, 'Conjuração'),
('Espirro Ácido', 'Bolha de ácido que causa 1d6 de dano ácido a até duas criaturas próximas.', '1 ação', 18, 'Instantânea', '1d6', TRUE, TRUE, FALSE, 0, 'Conjuração'),
('Esquentar Metal', 'Faz um objeto de metal brilhar incandescente causando 2d8 de dano de fogo.', '1 ação', 18, 'Concentração, até 1 minuto', '2d8', TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Estabilizar', 'Toca uma criatura com 0 PV para estabilizá-la imediatamente.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, FALSE, 0, 'Necromancia'),
('Explosão Solar', 'Luz solar brilhante causa 12d6 de dano radiante e cegueira.', '1 ação', 45, 'Instantânea', '12d6', TRUE, TRUE, TRUE, 8, 'Evocação'),
('Fabricar', 'Converte matéria-prima em produtos manufaturados do mesmo material.', '10 minutos', 36, 'Instantânea', NULL, TRUE, TRUE, FALSE, 4, 'Transmutação'),
('Falar com Animais', 'Permite compreender e se comunicar verbalmente com bestas.', '1 ação', 0, '10 minutos', NULL, TRUE, TRUE, FALSE, 1, 'Adivinhação'),
('Falar com os Mortos', 'Anima o espírito de um cadáver para que ele responda até cinco perguntas.', '1 ação', 3, '10 minutos', NULL, TRUE, TRUE, TRUE, 3, 'Necromancia'),
('Falar com Plantas', 'Imbui plantas com consciência limitada permitindo comunicação e comandos simples.', '1 ação', 0, '10 minutos', NULL, TRUE, TRUE, FALSE, 3, 'Adivinhação'),
('Flecha Ácida de Melf', 'Flecha de ácido que causa 4d4 de dano inicial e 2d4 no próximo turno.', '1 ação', 36, 'Instantânea', '4d4', TRUE, TRUE, TRUE, 2, 'Evocação'),
('Flecha Relampejante', 'Transforma munição em um relâmpago que causa 4d8 de dano elétrico ao alvo.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '4d8', TRUE, TRUE, FALSE, 3, 'Transmutação'),
('Fogo das Fadas', 'Delineia objetos e criaturas com luz facilitando ataques contra eles.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, FALSE, FALSE, 1, 'Evocação'),
('Fome de Hadar', 'Esfera de escuridão que causa dano de frio e dano de ácido de tentáculos.', '1 ação', 45, 'Concentração, até 1 minuto', '2d6', TRUE, TRUE, TRUE, 3, 'Conjuração'),
('Força Fantasmagórica', 'Cria uma ilusão na mente do alvo que pode causar 1d6 de dano psíquico.', '1 ação', 18, 'Concentração, até 1 minuto', '1d6', TRUE, TRUE, TRUE, 2, 'Ilusão'),
('Forjar Morte', 'Coloca uma criatura em estado catatônico indistinguível da morte.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, TRUE, 3, 'Necromancia'),
('Forma Etérea', 'Você entra nas fronteiras do Plano Etéreo podendo se mover através de objetos.', '1 ação', 0, 'Até 8 horas', NULL, TRUE, TRUE, FALSE, 7, 'Transmutação'),
('Forma Gasosa', 'Transforma uma criatura voluntária em uma nuvem nebulosa com voo.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 3, 'Transmutação'),
('Formas Animais', 'Transforma qualquer quantidade de aliados em bestas de ND 4 ou inferior.', '1 ação', 9, 'Concentração, até 24 horas', NULL, TRUE, TRUE, FALSE, 8, 'Transmutação'),
('Glifo de Vigilância', 'Inscreve um glifo que ativa runas explosivas (5d8) ou armazena uma magia.', '1 hora', 1, 'Até ser dissipada', '5d8', TRUE, TRUE, TRUE, 3, 'Abjuração'),
('Globo de Invulnerabilidade', 'Barreira que bloqueia qualquer magia de 5 nível ou inferior conjurada de fora.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 6, 'Abjuração'),
('Globos de Luz', 'Cria até quatro luzes que podem assumir forma humana luminosa.', '1 ação', 36, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 0, 'Evocação'),
('Golpe Constritor', 'Ataque com arma que faz brotar vinhas espinhentas causando 1d6 de dano.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '1d6', TRUE, FALSE, FALSE, 1, 'Conjuração'),
('Guardião da Fé', 'Guardião espectral que causa 20 de dano radiante a inimigos próximos.', '1 ação', 9, '8 horas', '20', TRUE, FALSE, FALSE, 4, 'Conjuração'),
('Heroísmo', 'Imbuí uma criatura com bravura, tornando-a imune a medo e dando PV temporário.', '1 ação', 1, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 1, 'Encantamento'),
('Identificação', 'Revela propriedades mágicas de um objeto ou magias afetando uma criatura.', '1 minuto', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 1, 'Adivinhação'),
('Idiomas', 'Garante a habilidade de compreender e falar qualquer idioma ouvido.', '1 ação', 1, '1 hora', NULL, TRUE, FALSE, TRUE, 3, 'Adivinhação'),
('Ilusão Menor', 'Cria um som ou imagem de um objeto de até 1,5 metro cúbico.', '1 ação', 9, '1 minuto', NULL, FALSE, FALSE, TRUE, 0, 'Ilusão'),
('Ilusão Programada', 'Cria uma ilusão complexa que se ativa sob uma condição específica.', '1 ação', 36, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 6, 'Ilusão'),
('Imagem Maior', 'Cria uma ilusão de até 6 metros cúbicos com sons, cheiros e temperatura.', '1 ação', 36, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 3, 'Ilusão'),
('Imagem Silenciosa', 'Cria uma imagem visual puramente visual de até 4,5 metros cúbicos.', '1 ação', 18, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 1, 'Ilusão'),
('Imobilizar Monstro', 'Paralisa uma criatura que falhar no teste de resistência de Sabedoria.', '1 ação', 27, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 5, 'Encantamento'),
('Imobilizar Pessoa', 'Paralisa um humanoide que falhar no teste de resistência de Sabedoria.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 2, 'Encantamento'),
('Infligir Ferimentos', 'Ataque corpo-a-corpo com magia que causa 3d10 de dano necrótico.', '1 ação', 1, 'Instantânea', '3d10', TRUE, TRUE, FALSE, 1, 'Necromancia'),
('Inseto Gigante', 'Transforma insetos comuns em versões gigantes sob seu comando.', '1 ação', 9, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 4, 'Transmutação'),
('Inverter a Gravidade', 'Inverte a gravidade em um cilindro fazendo criaturas e objetos caírem para cima.', '1 ação', 30, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 7, 'Transmutação'),
('Invisibilidade', 'Torna uma criatura e seus pertences invisíveis por uma hora ou até atacar.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Ilusão'),
('Invisibilidade Maior', 'Torna uma criatura invisível sem que a magia quebre ao atacar ou conjurar.', '1 ação', 1, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 4, 'Ilusão'),
('Invocação Instantânea de Drawmij', 'Marca um item para ser transportado instantaneamente para suas mãos.', '1 minuto', 1, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 6, 'Conjuração'),
('Isolamento', 'Esconde uma criatura ou objeto contra detecção e detém seu envelhecimento.', '1 ação', 1, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 7, 'Transmutação'),
('Labirinto', 'Bane uma criatura para um semiplano labiríntico até que ela consiga escapar.', '1 ação', 18, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 8, 'Conjuração'),
('Lâmina Flamejante', 'Evoca uma cimitarra de chamas que causa 3d6 de dano de fogo.', '1 ação bônus', 0, 'Concentração, até 10 minutos', '3d6', TRUE, TRUE, TRUE, 2, 'Evocação'),
('Lentidão', 'Reduz deslocamento, CA e limita ações de até seis criaturas.', '1 ação', 36, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 3, 'Transmutação'),
('Leque Cromático', 'Feixe ofuscante de luzes que deixa criaturas cegas baseado em seus PV.', '1 ação', 0, '1 rodada', NULL, TRUE, TRUE, TRUE, 1, 'Ilusão'),
('Levitação', 'Ergue uma criatura ou objeto até 6 metros verticalmente.', '1 ação', 18, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Ligação Telepática de Rary', 'Forja ligação psíquica entre até oito criaturas permitindo comunicação.', '1 ação', 9, '1 hora', NULL, TRUE, TRUE, TRUE, 5, 'Adivinhação'),
('Limpar a Mente', 'Concede imunidade a dano psíquico, leitura de pensamentos e encanto.', '1 ação', 1, '24 horas', NULL, TRUE, TRUE, FALSE, 8, 'Abjuração'),
('Localizar Animais ou Plantas', 'Descobre a direção de um tipo específico de besta ou planta.', '1 ação', 0, 'Instantânea', NULL, TRUE, TRUE, TRUE, 2, 'Adivinhação'),
('Localizar Criatura', 'Sente a direção da localização de uma criatura familiar a até 300 metros.', '1 ação', 0, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 4, 'Adivinhação'),
('Localizar Objeto', 'Sente a direção da localização de um objeto familiar a até 300 metros.', '1 ação', 0, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 2, 'Adivinhação'),
('Loquacidade', 'Substitui resultados de testes de Carisma por 15 e garante sinceridade mágica.', '1 ação', 0, '1 hora', NULL, TRUE, FALSE, FALSE, 8, 'Transmutação'),
('Lufada de Vento', 'Linha de vento forte que empurra criaturas e apaga chamas.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 2, 'Evocação'),
('Luz', 'Objeto emite luz plena num raio de 6 metros por uma hora.', '1 ação', 1, '1 hora', NULL, TRUE, FALSE, TRUE, 0, 'Evocação'),
('Luz do Dia', 'Esfera de 18 metros de raio que produz luz plena e dissipa escuridão mágica.', '1 ação', 18, '1 hora', NULL, TRUE, TRUE, FALSE, 3, 'Evocação'),
('Malogro', 'Drena vitalidade causando 8d8 de dano necrótico, especialmente eficaz em plantas.', '1 ação', 9, 'Instantânea', '8d8', TRUE, TRUE, FALSE, 4, 'Necromancia'),
('Mansão Magnífica de Mordenkainen', 'Conjura uma residência extradimensional luxuosa com servos e banquetes.', '1 minuto', 90, '24 horas', NULL, TRUE, TRUE, TRUE, 7, 'Conjuração'),
('Manto do Cruzado', 'Aura que faz aliados causarem 1d4 de dano radiante extra com ataques.', '1 ação', 0, 'Concentração, até 1 minuto', '1d4', TRUE, FALSE, FALSE, 3, 'Evocação'),
('Mão de Bigby', 'Cria uma mão de energia que pode esmagar, empurrar ou socar (4d8 de dano).', '1 ação', 36, 'Concentração, até 1 minuto', '4d8', TRUE, TRUE, TRUE, 5, 'Evocação'),
('Mãos Flamejantes', 'Leque de chamas que causa 3d6 de dano de fogo em um cone de 4,5 metros.', '1 ação', 0, 'Instantânea', '3d6', TRUE, TRUE, FALSE, 1, 'Evocação'),
('Mãos Mágicas', 'Cria uma mão espectral que pode manipular objetos a até 9 metros.', '1 ação', 9, '1 minuto', NULL, TRUE, TRUE, FALSE, 0, 'Conjuração'),
('Marca da Punição', 'Ataque causa 2d6 de dano radiante extra e impede que o alvo fique invisível.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '2d6', TRUE, FALSE, FALSE, 2, 'Evocação'),
('Marca do Caçador', 'Marca uma presa causando 1d6 de dano extra e facilitando o rastreio.', '1 ação bônus', 27, 'Concentração, até 1 hora', '1d6', TRUE, FALSE, FALSE, 1, 'Adivinhação'),
('Medo', 'Projeta imagem fantasmagórica que amedronta criaturas em um cone de 9 metros.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 3, 'Ilusão'),
('Mensageiro Animal', 'Usa uma besta miúda para entregar uma mensagem de até 25 palavras.', '1 ação', 9, '24 horas', NULL, TRUE, TRUE, TRUE, 2, 'Encantamento'),
('Mensagem', 'Sussurra uma mensagem que apenas o alvo ouve e pode responder.', '1 ação', 36, '1 rodada', NULL, TRUE, TRUE, TRUE, 0, 'Transmutação'),
('Mesclar-se às Rochas', 'Você se funde a uma superfície rochosa com todo seu equipamento.', '1 ação', 1, '8 horas', '6d6', TRUE, TRUE, FALSE, 3, 'Transmutação'),
('Metamorfose', 'Transforma uma criatura em uma besta de ND igual ou menor que o alvo.', '1 ação', 18, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 4, 'Transmutação'),
('Metamorfose Verdadeira', 'Transforma criatura em criatura, objeto em criatura ou criatura em objeto permanentemente.', '1 ação', 9, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 9, 'Transmutação'),
('Miragem', 'Altera o terreno de uma área de 1,5 quilômetro incluindo elementos sensoriais.', '10 minutos', 500, '10 dias', NULL, TRUE, TRUE, FALSE, 7, 'Ilusão'),
('Missão', 'Impõe um comando mágico que causa 5d6 de dano psíquico se for desobedecido.', '1 minuto', 18, '30 dias', '5d6', TRUE, FALSE, FALSE, 5, 'Encantamento'),
('Mísseis Mágicos', 'Cria três dardos que causam 1d4 + 1 de dano de energia cada e nunca erram.', '1 ação', 36, 'Instantânea', '1d4+1', TRUE, TRUE, FALSE, 1, 'Evocação'),
('Modificar Memória', 'Tenta alterar as memórias de um evento de até 10 minutos de outra criatura.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 5, 'Encantamento'),
('Moldar Rochas', 'Modela um objeto de pedra médio em qualquer forma desejada.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 4, 'Transmutação'),
('Montaria Fantasmagórica', 'Conjura uma criatura Grande quase-real similar a um cavalo para cavalgar.', '1 minuto', 9, '1 hora', NULL, TRUE, TRUE, FALSE, 3, 'Ilusão'),
('Mover Terra', 'Remodela áreas de terra, areia ou barro ao longo de 10 minutos.', '1 ação', 36, 'Concentração, até 2 horas', NULL, TRUE, TRUE, TRUE, 6, 'Transmutação'),
('Movimentação Livre', 'Alvo ignora terreno difícil e efeitos mágicos que reduzem deslocamento.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, TRUE, 4, 'Abjuração'),
('Muralha de Energia', 'Cria uma barreira invisível e imune a danos feita de energia mágica.', '1 ação', 36, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 5, 'Evocação'),
('Muralha de Espinhos', 'Cria muralha de arbustos espinhosos que causa 7d8 de dano perfurante.', '1 ação', 36, 'Concentração, até 10 minutos', '7d8', TRUE, TRUE, TRUE, 6, 'Conjuração'),
('Muralha de Fogo', 'Muralha opaca que causa 5d8 de dano de fogo a quem se aproximar.', '1 ação', 36, 'Concentração, até 1 minuto', '5d8', TRUE, TRUE, TRUE, 4, 'Evocação'),
('Muralha de Gelo', 'Cria muralha de gelo que causa 10d6 de dano ao surgir e dano de frio ao ser atravessada.', '1 ação', 36, 'Concentração, até 10 minutos', '10d6', TRUE, TRUE, TRUE, 6, 'Evocação'),
('Muralha de Pedra', 'Cria muralha de rocha sólida não-mágica que pode se tornar permanente.', '1 ação', 36, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 5, 'Conjuração'),
('Muralha de Vento', 'Muralha de ventos fortes que causa 3d8 de dano e deflete projéteis.', '1 ação', 36, 'Concentração, até 1 minuto', '3d8', TRUE, TRUE, TRUE, 3, 'Evocação'),
('Muralha Prismática', 'Muralha multicolorida com sete camadas de efeitos diferentes (10d6 de dano cada).', '1 ação', 18, '10 minutos', '10d6', TRUE, TRUE, FALSE, 9, 'Abjuração'),
('Nevasca', 'Chuva congelante e neve criam área de escuridão densa e terreno difícil.', '1 ação', 45, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 3, 'Conjuração'),
('Névoa Fétida', 'Esfera de gás amarelado que faz criaturas perderem sua ação vomitando.', '1 ação', 27, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 3, 'Conjuração'),
('Névoa Mortal', 'Esfera de nevoeiro venenoso que causa 5d8 de dano de veneno.', '1 ação', 36, 'Concentração, até 10 minutos', '5d8', TRUE, TRUE, FALSE, 5, 'Conjuração'),
('Névoa Obscurecente', 'Esfera de névoa que gera escuridão densa em uma área de 6 metros.', '1 ação', 36, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 1, 'Conjuração'),
('Nublar', 'Seu corpo se torna turvo, dando desvantagem em ataques contra você.', '1 ação', 0, 'Concentração, até 1 minuto', NULL, TRUE, FALSE, FALSE, 2, 'Ilusão'),
('Nuvem de Adagas', 'Preenche um cubo com adagas giratórias que causam 4d4 de dano cortante.', '1 ação', 18, 'Concentração, até 1 minuto', '4d4', TRUE, TRUE, TRUE, 2, 'Conjuração'),
('Nuvem Incendiária', 'Nuvem de fumaça que dispara brasas causando 10d8 de dano de fogo.', '1 ação', 45, 'Concentração, até 1 minuto', '10d8', TRUE, TRUE, FALSE, 8, 'Conjuração'),
('Olho Arcano', 'Cria um olho invisível que você controla mentalmente para ver o ambiente.', '1 ação', 9, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 4, 'Adivinhação'),
('Onda Destrutiva', 'Explosão de energia divina causa 5d6 de trovão e 5d6 radiante/necrótico.', '1 ação', 0, 'Instantânea', '10d6', TRUE, FALSE, FALSE, 5, 'Evocação'),
('Onda Troveante', 'Onda de força que causa 2d8 de dano trovejante e empurra inimigos.', '1 ação', 0, 'Instantânea', '2d8', TRUE, TRUE, FALSE, 1, 'Evocação'),
('Oração Curativa', 'Até seis criaturas recuperam 2d8 + modificador de conjuração pontos de vida.', '10 minutos', 9, 'Instantânea', NULL, TRUE, FALSE, FALSE, 2, 'Evocação'),
('Orbe Cromática', 'Arremessa esfera de energia de um tipo escolhido causando 3d8 de dano.', '1 ação', 27, 'Instantânea', '3d8', TRUE, TRUE, TRUE, 1, 'Evocação'),
('Orientação', 'Concede um bônus de 1d4 a um teste de habilidade à escolha do alvo.', '1 ação', 1, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 0, 'Adivinhação'),
('Padrão Hipnótico', 'Padrão de cores que incapacita e deixa criaturas enfeitiçadas com deslocamento 0.', '1 ação', 36, 'Concentração, até 1 minuto', NULL, FALSE, TRUE, TRUE, 3, 'Ilusão'),
('Palavra Curativa', 'Uma criatura à vista recupera 1d4 + modificador de conjuração PV (ação bônus).', '1 ação bônus', 18, 'Instantânea', NULL, TRUE, FALSE, FALSE, 1, 'Evocação'),
('Palavra Curativa em Massa', 'Até seis criaturas recuperam 1d4 + modificador de conjuração PV (ação bônus).', '1 ação bônus', 18, 'Instantânea', NULL, TRUE, FALSE, FALSE, 3, 'Evocação'),
('Palavra de Poder Atordoar', 'Palavra que atordoa criaturas com 150 pontos de vida ou menos.', '1 ação', 18, 'Instantânea', NULL, TRUE, FALSE, FALSE, 8, 'Encantamento'),
('Palavra de Poder Curar', 'Onda de energia que restaura todos os pontos de vida e remove condições.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, FALSE, 9, 'Evocação'),
('Palavra de Poder Matar', 'Compele uma criatura com 100 PV ou menos a morrer instantaneamente.', '1 ação', 18, 'Instantânea', NULL, TRUE, FALSE, FALSE, 9, 'Encantamento'),
('Palavra de Recordação', 'Teletransporta você e aliados para um santuário previamente designado.', '1 ação', 1.5, 'Instantânea', NULL, TRUE, FALSE, FALSE, 6, 'Conjuração'),
('Palavra Divina', 'Profere palavra imbuída de poder que surda, cega, atordoa ou mata conforme os PV.', '1 ação bônus', 9, 'Instantânea', NULL, TRUE, FALSE, FALSE, 7, 'Evocação'),
('Parar o Tempo', 'Para o fluxo do tempo para todos menos para você por 1d4+1 turnos.', '1 ação', 0, 'Instantânea', NULL, TRUE, FALSE, FALSE, 9, 'Transmutação'),
('Passo Nebuloso', 'Você se teletransporta instantaneamente a até 9 metros para um espaço visível.', '1 ação bônus', 0, 'Instantânea', NULL, TRUE, FALSE, FALSE, 2, 'Conjuração'),
('Passos Longos', 'Aumenta o deslocamento de uma criatura em 3 metros por uma hora.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, TRUE, 1, 'Transmutação'),
('Passos Sem Pegadas', 'Bônus de +10 em Furtividade e impede de ser rastreado por meios mundanos.', '1 ação', 0, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Abjuração'),
('Patas de Aranha', 'Permite mover-se por superfícies verticais e tetos com mãos livres.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Pele de Árvore', 'A CA de uma criatura não pode ser inferior a 16 até o fim da magia.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Pele de Pedra', 'Pele do alvo torna-se rocha sólida dando resistência a danos físicos não-mágicos.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, TRUE, 4, 'Abjuração'),
('Pequena Cabana de Leomund', 'Domo imóvel que bloqueia magias e fornece ambiente seco para até nove criaturas.', '1 minuto', 0, '8 horas', NULL, TRUE, TRUE, TRUE, 3, 'Evocação'),
('Perdição', 'Alvos subtraem 1d4 de suas jogadas de ataque e testes de resistência.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Encantamento'),
('Piskar', '50% de chance de ir para o Plano Etéreo ao final de cada turno.', '1 ação', 0, '1 minuto', NULL, TRUE, TRUE, FALSE, 3, 'Transmutação'),
('Porta Dimensional', 'Teletransporta você e uma criatura voluntária para qualquer local em 150 metros.', '1 ação', 150, 'Instantânea', NULL, TRUE, FALSE, FALSE, 4, 'Conjuração'),
('Portal', 'Conjura um portal circular para uma localização precisa em outro plano.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 9, 'Conjuração'),
('Portal Arcano', 'Cria dois anéis dimensionais conectados por onde criaturas podem passar.', '1 ação', 150, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 6, 'Conjuração'),
('Praga', 'Seu toque inflige uma doença como Ardência Mental ou Necrose da Carne.', '1 ação', 1, '7 dias', NULL, TRUE, TRUE, FALSE, 5, 'Necromancia'),
('Praga de Insetos', 'Enxame voraz de gafanhotos que causa 4d10 de dano perfurante.', '1 ação', 90, 'Concentração, até 10 minutos', '4d10', TRUE, TRUE, TRUE, 5, 'Conjuração'),
('Prestidigitação', 'Realiza truques simples como limpar objetos, acender velas ou criar odores.', '1 ação', 3, 'Até 1 hora', NULL, TRUE, TRUE, FALSE, 0, 'Transmutação'),
('Prisão de Energia', 'Cela de energia invisível que impede saída por meios físicos ou mágicos.', '1 ação', 30, '1 hora', NULL, TRUE, TRUE, TRUE, 7, 'Evocação'),
('Proibição', 'Protege área contra teletransporte e causa 5d6 de dano a certos tipos de criaturas.', '10 minutos', 1, '1 dia', '5d6', TRUE, TRUE, TRUE, 6, 'Abjuração'),
('Projeção Astral', 'Projeta corpos astrais para o Plano Astral enquanto o físico dorme.', '1 hora', 3, 'Especial', NULL, TRUE, TRUE, TRUE, 9, 'Necromancia'),
('Projetar Imagem', 'Cria cópia ilusória sua que você pode controlar e ver/ouvir através dela.', '1 ação', 750000, 'Concentração, até 1 dia', NULL, TRUE, TRUE, TRUE, 7, 'Ilusão'),
('Proteção contra a Morte', 'Concede proteção que impede uma criatura de morrer na primeira vez que cair a 0 PV.', '1 ação', 1, '8 horas', NULL, TRUE, TRUE, FALSE, 4, 'Abjuração'),
('Proteção contra Energia', 'Concede resistência a um tipo de dano: ácido, elétrico, fogo, frio ou trovão.', '1 ação', 1, 'Concentração, até 1 hora', NULL, TRUE, TRUE, FALSE, 3, 'Abjuração'),
('Proteção contra Lâminas', 'Garante resistência contra dano físico de ataques com armas até o fim do próximo turno.', '1 ação', 0, '1 rodada', NULL, TRUE, TRUE, FALSE, 0, 'Abjuração'),
('Proteção contra o Bem e Mal', 'Protege contra aberrações, planares e mortos-vivos, dando desvantagem a eles.', '1 ação', 1, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 1, 'Abjuração'),
('Proteção contra Veneno', 'Neutraliza um veneno e dá vantagem em testes e resistência contra dano de veneno.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, FALSE, 2, 'Abjuração'),
('Proteger Fortaleza', 'Cria névoas, trancas mágicas, teias e outros efeitos em uma estrutura.', '10 minutos', 1, '24 horas', NULL, TRUE, TRUE, TRUE, 6, 'Abjuração'),
('Purificar Alimentos', 'Purifica comida e bebida não-mágica de venenos e doenças.', '1 ação', 3, 'Instantânea', NULL, TRUE, TRUE, FALSE, 1, 'Transmutação'),
('Queda Suave', 'Reduz a velocidade de queda de até cinco criaturas para evitar dano.', '1 reação', 18, '1 minuto', NULL, TRUE, FALSE, TRUE, 1, 'Transmutação'),
('Raio Adoecente', 'Raio de energia esverdeada que causa 2d8 de dano de veneno e envenena o alvo.', '1 ação', 18, 'Instantânea', '2d8', TRUE, TRUE, FALSE, 1, 'Necromancia'),
('Raio Ardente', 'Dispara três raios de fogo que causam 2d6 de dano cada.', '1 ação', 36, 'Instantânea', '2d6', TRUE, TRUE, FALSE, 2, 'Evocação'),
('Raio de Bruxa', 'Raio elétrico que mantém um arco contínuo causando 1d12 de dano por turno.', '1 ação', 9, 'Concentração, até 1 minuto', '1d12', TRUE, TRUE, TRUE, 1, 'Evocação'),
('Raio de Fogo', 'Arremessa um cisco de fogo que causa 1d10 de dano de fogo.', '1 ação', 36, 'Instantânea', '1d10', TRUE, TRUE, FALSE, 0, 'Evocação'),
('Raio de Gelo', 'Raio frigido que causa 1d8 de dano de frio e reduz deslocamento em 3 metros.', '1 ação', 18, 'Instantânea', '1d8', TRUE, TRUE, FALSE, 0, 'Evocação'),
('Raio do Enfraquecimento', 'Raio que faz com que o alvo cause apenas metade do dano com ataques de Força.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 2, 'Necromancia'),
('Raio Guiador', 'Raio que causa 4d6 de dano radiante e dá vantagem no próximo ataque contra o alvo.', '1 ação', 36, '1 rodada', '4d6', TRUE, TRUE, FALSE, 1, 'Evocação'),
('Raio Lunar', 'Cilindro de luz prateada que causa 2d10 de dano radiante e revela metamorfos.', '1 ação', 36, 'Concentração, até 1 minuto', '2d10', TRUE, TRUE, TRUE, 2, 'Evocação'),
('Raio Solar', 'Cria linha de radiação luminosa que causa 6d8 de dano radiante e cega.', '1 ação', 0, 'Concentração, até 1 minuto', '6d8', TRUE, TRUE, TRUE, 6, 'Evocação'),
('Rajada de Veneno', 'Sopro de gás tóxico que causa 1d12 de dano de veneno.', '1 ação', 3, 'Instantânea', '1d12', TRUE, TRUE, FALSE, 0, 'Conjuração'),
('Rajada Mística', 'Feixe de energia crepitante que causa 1d10 de dano de energia.', '1 ação', 36, 'Instantânea', '1d10', TRUE, TRUE, FALSE, 0, 'Evocação'),
('Rajada Prismática', 'Oito raios coloridos com efeitos diversos como fogo, ácido, sono ou banimento.', '1 ação', 0, 'Instantânea', '10d6', TRUE, TRUE, FALSE, 7, 'Evocação'),
('Recipiente Arcano', 'Sua alma entra em um recipiente e pode possuir corpos de humanoides próximos.', '1 minuto', 0, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 6, 'Necromancia'),
('Recuo Acelerado', 'Permite realizar a ação de Disparada como uma ação bônus em cada turno.', '1 ação bônus', 0, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 1, 'Transmutação'),
('Reencarnação', 'Traz um humanoide morto de volta à vida em um novo corpo de raça aleatória.', '1 hora', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 5, 'Transmutação'),
('Reflexos', 'Cria três duplicatas ilusórias suas que podem ser alvos de ataques em seu lugar.', '1 ação', 0, '1 minuto', NULL, TRUE, TRUE, FALSE, 2, 'Ilusão'),
('Regeneração', 'Restaura 4d8 + 15 pontos de vida iniciais e cura membros decepados gradualmente.', '1 minuto', 1, '1 hora', '4d8+15', TRUE, TRUE, TRUE, 7, 'Transmutação'),
('Relâmpago', 'Linha de eletricidade de 30 metros que causa 8d6 de dano elétrico.', '1 ação', 0, 'Instantânea', '8d6', TRUE, TRUE, TRUE, 3, 'Evocação'),
('Remover Maldição', 'Encerra todas as maldições afetando uma criatura ou objeto ao seu toque.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, FALSE, 3, 'Abjuração'),
('Repouso Tranquilo', 'Protege um corpo contra decomposição e impede que se torne um morto-vivo.', '1 ação', 1, '10 dias', NULL, TRUE, TRUE, TRUE, 2, 'Necromancia'),
('Repreensão Infernal', 'Criatura que lhe causou dano é envolvida por chamas causando 2d10 de fogo.', '1 reação', 18, 'Instantânea', '2d10', TRUE, TRUE, FALSE, 1, 'Evocação'),
('Resistência', 'Concede bônus de 1d4 a um teste de resistência à escolha do alvo.', '1 ação', 1, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 0, 'Abjuração'),
('Respirar na Água', 'Até dez criaturas voluntárias podem respirar embaixo dágua por 24 horas.', '1 ação', 9, '24 horas', NULL, TRUE, TRUE, TRUE, 3, 'Transmutação'),
('Ressurreição', 'Traz de volta à vida criatura morta a até um século com todos PV.', '1 hora', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 7, 'Necromancia'),
('Ressurreição Verdadeira', 'Traz de volta criatura morta a até 200 anos restaurando órgãos e membros.', '1 hora', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 9, 'Necromancia'),
('Restauração Maior', 'Desfaz efeitos debilitantes como exaustão, petrificação ou redução de atributos.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 5, 'Abjuração'),
('Restauração Menor', 'Acaba com doenças ou condições como cego, surdo, paralisado ou envenenado.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, FALSE, 2, 'Abjuração'),
('Reviver os Mortos', 'Traz criatura morta a até 10 dias de volta com 1 ponto de vida.', '1 hora', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 5, 'Necromancia'),
('Revivificar', 'Toca criatura morta no último minuto para trazê-la de volta com 1 PV.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 3, 'Necromancia'),
('Riso Histérico de Tasha', 'Faz criatura cair na gargalhada, ficando caída e incapacitada.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Encantamento'),
('Rogar Maldição', 'Amaldiçoa criatura impondo desvantagens ou dano extra de 1d8 necrótico.', '1 ação', 1, 'Concentração, até 1 minuto', '1d8', TRUE, TRUE, FALSE, 3, 'Necromancia'),
('Salto', 'Triplica a distância de salto de uma criatura por um minuto.', '1 ação', 1, '1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Transmutação'),
('Santuário', 'Protege criatura forçando atacantes a passarem em teste de Sabedoria.', '1 ação bônus', 9, '1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Abjuração'),
('Santuário Particular de Mordenkainen', 'Segura uma área contra som, visão, teletransporte e sensores de vidência.', '10 minutos', 36, '24 horas', NULL, TRUE, TRUE, TRUE, 4, 'Abjuração'),
('Saraivada de Espinhos', 'Ataque à distância que cria chuva de espinhos causando 1d10 de dano.', '1 ação bônus', 0, 'Concentração, até 1 minuto', '1d10', TRUE, FALSE, FALSE, 1, 'Conjuração'),
('Semiplano', 'Cria uma porta para um semiplano vazio de 9 metros quadrados.', '1 ação', 18, '1 hora', NULL, TRUE, FALSE, FALSE, 8, 'Conjuração'),
('Sentido Bestial', 'Permite ver e ouvir através dos sentidos de uma besta voluntária.', '1 ação', 1, 'Concentração, até 1 hora', NULL, FALSE, TRUE, FALSE, 2, 'Adivinhação'),
('Servo Invisível', 'Força invisível sem mente que realiza tarefas simples ao seu comando.', '1 ação', 18, '1 hora', NULL, TRUE, TRUE, TRUE, 1, 'Conjuração'),
('Sexto Sentido', 'Garante vantagem em ataques/testes e impede que o alvo seja surpreendido.', '1 minuto', 1, '8 horas', NULL, TRUE, TRUE, TRUE, 9, 'Adivinhação'),
('Silêncio', 'Esfera de 6 metros onde nenhum som pode ser criado ou atravessado.', '1 ação', 36, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 2, 'Ilusão'),
('Símbolo', 'Inscreve glifo nocivo que causa efeitos como morte (10d10), dor ou insanidade.', '1 minuto', 1, 'Até ser dissipada', '10d10', TRUE, TRUE, TRUE, 7, 'Abjuração'),
('Similaridade', 'Muda a aparência física e pertences de qualquer quantidade de criaturas.', '1 ação', 9, '8 horas', NULL, TRUE, TRUE, FALSE, 5, 'Ilusão'),
('Simulacro', 'Cria duplicata ilusória de gelo de uma besta ou humanoide sob seu controle.', '12 horas', 1, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 7, 'Ilusão'),
('Sinal de Esperança', 'Dá vantagem em testes de Sabedoria/Morte e maximiza curas recebidas.', '1 ação', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 3, 'Abjuração'),
('Sonho', 'Entra nos sonhos de uma criatura para conversar ou criar pesadelos (3d6 dano).', '1 minuto', 9999, '8 horas', '3d6', TRUE, TRUE, TRUE, 5, 'Ilusão'),
('Sono', 'Coloca criaturas em entorpecimento mágico baseado em seus pontos de vida.', '1 ação', 36, '1 minuto', NULL, TRUE, TRUE, TRUE, 1, 'Encantamento'),
('Sugestão', 'Sugere um curso de atividade razoável que o alvo é compelido a seguir.', '1 ação', 9, 'Concentração, até 8 horas', NULL, TRUE, FALSE, TRUE, 2, 'Encantamento'),
('Sugestão em Massa', 'Sugere atividade razoável para até doze criaturas por 24 horas.', '1 ação', 18, '24 horas', NULL, TRUE, FALSE, TRUE, 6, 'Encantamento'),
('Sussurros Dissonantes', 'Melodia que causa 3d6 de dano psíquico e força o alvo a fugir.', '1 ação', 18, 'Instantânea', '3d6', TRUE, FALSE, FALSE, 1, 'Encantamento'),
('Taumaturgia', 'Manifesta pequenas maravilhas como tremores, sons ou alteração de olhos.', '1 ação', 9, 'Até 1 minuto', NULL, TRUE, FALSE, FALSE, 0, 'Transmutação'),
('Teia', 'Massa de teias pegajosas que impede o movimento e causa 2d4 de dano se queimar.', '1 ação', 18, 'Concentração, até 1 hora', '2d4', TRUE, TRUE, TRUE, 2, 'Conjuração'),
('Telecinésia', 'Move ou manipula criaturas e objetos através do pensamento.', '1 ação', 18, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, FALSE, 5, 'Transmutação'),
('Telepatia', 'Forja ligação telepática ilimitada entre você e uma criatura familiar.', '1 ação', 9999, '24 horas', NULL, TRUE, TRUE, TRUE, 8, 'Adivinhação'),
('Teletransporte', 'Transporta você e até oito aliados para um destino conhecido no mesmo plano.', '1 ação', 3, 'Instantânea', '3d10', TRUE, FALSE, FALSE, 7, 'Conjuração'),
('Teletransporte por Árvores', 'Cria ligação entre duas árvores permitindo transporte entre elas.', '1 ação', 3, '1 rodada', NULL, TRUE, TRUE, FALSE, 6, 'Conjuração'),
('Tempestade da Vingança', 'Nuvem que causa trovão, chuva ácida, relâmpagos (10d6) e frio.', '1 ação', 500, 'Concentração, até 1 minuto', '2d6', TRUE, TRUE, FALSE, 9, 'Conjuração'),
('Tempestade de Fogo', 'Chamas crepitantes que causam 7d10 de dano de fogo em cubos organizáveis.', '1 ação', 45, 'Instantânea', '7d10', TRUE, TRUE, FALSE, 7, 'Evocação'),
('Tempestade de Gelo', 'Granizo em cilindro causa 2d8 de concussão e 4d6 de frio.', '1 ação', 90, 'Instantânea', '2d8', TRUE, TRUE, TRUE, 4, 'Evocação'),
('Tentáculos Negros de Evard', 'Tentáculos que tornam solo terreno difícil e causam 3d6 de dano de concussão.', '1 ação', 27, 'Concentração, até 1 minuto', '3d6', TRUE, TRUE, TRUE, 4, 'Conjuração'),
('Terremoto', 'Tremor intenso de 30 metros de raio que derruba estruturas e abre fissuras.', '1 ação', 150, 'Concentração, até 1 minuto', '50', TRUE, TRUE, TRUE, 8, 'Evocação'),
('Terreno Alucinógeno', 'Faz terreno natural parecer, soar e cheirar como outro tipo de terreno.', '10 minutos', 90, '24 horas', NULL, TRUE, TRUE, TRUE, 4, 'Ilusão'),
('Toque Arrepiante', 'Mão fantasmagórica causa 1d8 necrótico e impede recuperação de PV.', '1 ação', 36, '1 rodada', '1d8', TRUE, TRUE, FALSE, 0, 'Necromancia'),
('Toque Chocante', 'Choque elétrico causa 1d8 de dano e impede reações do alvo.', '1 ação', 1, 'Instantânea', '1d8', TRUE, TRUE, FALSE, 0, 'Evocação'),
('Toque Vampírico', 'Drena força vital causando 3d6 de dano necrótico e curando você.', '1 ação', 0, 'Concentração, até 1 minuto', '3d6', TRUE, TRUE, FALSE, 3, 'Necromancia'),
('Tranca Arcana', 'Tranca porta ou baú magicamente, aumentando a dificuldade de arrombamento.', '1 ação', 1, 'Até ser dissipada', NULL, TRUE, TRUE, TRUE, 2, 'Abjuração'),
('Truque de Corda', 'Corda ergue-se para um espaço extradimensional seguro para até oito criaturas.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Tsunami', 'Muralha de água de 90 metros causa 6d10 de dano e arrasta criaturas.', '1 minuto', 500, 'Concentração, até 6 rodadas', '6d10', TRUE, TRUE, FALSE, 8, 'Conjuração'),
('Velocidade', 'Dobra deslocamento, dá +2 na CA e uma ação adicional ao alvo.', '1 ação', 18, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, TRUE, 3, 'Transmutação'),
('Ver o Invisível', 'Permite enxergar criaturas e objetos invisíveis e ver no Plano Etéreo.', '1 ação', 0, '1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Adivinhação'),
('Viagem Planar', 'Transporta até oito criaturas para outro plano de existência.', '1 ação', 1, 'Instantânea', NULL, TRUE, TRUE, TRUE, 7, 'Conjuração'),
('Vidência', 'Cria sensor para ver e ouvir criatura ou local em particular à distância.', '10 minutos', 0, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 5, 'Adivinhação'),
('Vínculo Protetor', 'Cria elo onde o alvo ganha +1 na CA/testes e divide dano sofrido com você.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, TRUE, 2, 'Abjuração'),
('Vinha Esmagadora', 'Vinhas que enlaçam e arrastam criaturas em sua direção.', '1 ação bônus', 9, 'Concentração, até 1 minuto', NULL, TRUE, TRUE, FALSE, 4, 'Conjuração'),
('Visão da Verdade', 'Concede visão verdadeira percebendo portas secretas e o Plano Etéreo.', '1 ação', 1, '1 hora', NULL, TRUE, TRUE, TRUE, 6, 'Adivinhação'),
('Visão no Escuro', 'Garante visão no escuro com alcance de 18 metros.', '1 ação', 1, '8 horas', NULL, TRUE, TRUE, TRUE, 2, 'Transmutação'),
('Vitalidade Falsa', 'Garante 1d4 + 4 pontos de vida temporários.', '1 ação', 0, '1 hora', '1d4+4', TRUE, TRUE, TRUE, 1, 'Necromancia'),
('Voo', 'Garante deslocamento de voo de 18 metros por dez minutos.', '1 ação', 1, 'Concentração, até 10 minutos', NULL, TRUE, TRUE, TRUE, 3, 'Transmutação'),
('Zombaria Viciosa', 'Insultos que causam 1d4 de dano psíquico e desvantagem no próximo ataque.', '1 ação', 18, 'Instantânea', '1d4', TRUE, FALSE, FALSE, 0, 'Encantamento'),
('Zona da Verdade', 'Criaturas na esfera não podem mentir deliberadamente.', '1 ação', 18, '10 minutos', NULL, TRUE, TRUE, FALSE, 2, 'Encantamento');

SELECT setval(pg_get_serial_sequence('Spell', 'id_spell'), (SELECT MAX(id_spell) FROM Spell));